### ISSUE TITLE
Array prototype concatenation

### ISSUE THREAD

**Issue by paranoidi** [PiotrDabkowski/Js2Py#1]
Running "(1+[])" will result "1[]" instead of "1" which it should be. I assume this is because of unfinished array prototype? Any plans to make this work? :)

**Comment by PiotrDabkowski** [comment]
I will try to fix it next week, thanks. There are many minor errors that require a fix but it will take a considerable amount of time. Since this project has a very small number of users I dont know whether its worth spending much time on it :)
