### ISSUE TITLE
some py2 code  appeared when do "pip3 install js2py"

### ISSUE THREAD

**Issue by ihgazni2** [PiotrDabkowski/Js2Py#106]
#pip3 install js2py
Downloading/unpacking js2py
  Downloading Js2Py-0.58.tar.gz (556kB): 556kB downloaded
  Running setup.py (path:/tmp/pip_build_root/js2py/setup.py) egg_info for package js2py
Downloading/unpacking tzlocal>=1.2 (from js2py)
  Downloading tzlocal-1.5.1.tar.gz
  Running setup.py (path:/tmp/pip_build_root/tzlocal/setup.py) egg_info for package tzlocal
Requirement already satisfied (use --upgrade to upgrade): six>=1.10 in /usr/local/lib/python3.4/site-packages (from js2py)
Downloading/unpacking pyjsparser>=2.5.1 (from js2py)
  Downloading pyjsparser-2.5.2.tar.gz
  Running setup.py (path:/tmp/pip_build_root/pyjsparser/setup.py) egg_info for package pyjsparser
Downloading/unpacking pytz (from tzlocal>=1.2->js2py)
  Downloading pytz-2017.3-py2.py3-none-any.whl (511kB): 511kB downloaded
Installing collected packages: js2py, tzlocal, pyjsparser, pytz
  **Running setup.py install for js2py
      File "/usr/local/lib/python3.4/site-packages/js2py/test_internals.py", line 9
        print seval.eval_js_vm(x)
                  ^
    SyntaxError: invalid syntax
    
      File "/usr/local/lib/python3.4/site-packages/js2py/internals/byte_trans.py", line 685
        print a.declared_vars
              ^
    SyntaxError: Missing parentheses in call to 'print'
    
      File "/usr/local/lib/python3.4/site-packages/js2py/internals/opcodes.py", line 653
        print typ
                ^
    SyntaxError: Missing parentheses in call to 'print'**
    
      File "/usr/local/lib/python3.4/site-packages/js2py/internals/constructors/jsfunction.py", line 68
        print ' '.join(map(to_string, args))
                ^
    SyntaxError: invalid syntax
    
      File "/usr/local/lib/python3.4/site-packages/js2py/internals/speed.py", line 50
        print timeit(
                   ^
    SyntaxError: invalid syntax
    
  Could not find .egg-info directory in install record for js2py
  Running setup.py install for tzlocal
  Could not find .egg-info directory in install record for tzlocal>=1.2 (from js2py)
  Running setup.py install for pyjsparser
  Could not find .egg-info directory in install record for pyjsparser>=2.5.1 (from js2py)
Successfully installed js2py tzlocal pyjsparser pytz
Cleaning up...
#

**Comment by ape364** [comment]
same error while building in docker (image `python:3.6.4`)

**Comment by jnweiger** [comment]
Cannot reproduce that issue:
```
# pip3 install js2py
Collecting js2py
  Downloading https://files.pythonhosted.org/packages/ef/1d/763ddc32da7519de26249a47483587741cc0a93ed1ddf71b2ac2c98c4e84/Js2Py-0.59.tar.gz (556kB)
    100% |████████████████████████████████| 563kB 421kB/s 
Collecting tzlocal>=1.2 (from js2py)
  Downloading https://files.pythonhosted.org/packages/cb/89/e3687d3ed99bc882793f82634e9824e62499fdfdc4b1ae39e211c5b05017/tzlocal-1.5.1.tar.gz
Requirement already satisfied: six>=1.10 in /usr/lib/python3/dist-packages (from js2py)
Collecting pyjsparser>=2.5.1 (from js2py)
  Downloading https://files.pythonhosted.org/packages/17/3d/59f7f0cd6a7cdab611b36d8921c9d2d6c5564033d938ec2eb934cdca0e48/pyjsparser-2.5.2.tar.gz
Collecting pytz (from tzlocal>=1.2->js2py)
  Downloading https://files.pythonhosted.org/packages/dc/83/15f7833b70d3e067ca91467ca245bae0f6fe56ddc7451aa0dc5606b120f2/pytz-2018.4-py2.py3-none-any.whl (510kB)
    100% |████████████████████████████████| 512kB 203kB/s 
Installing collected packages: pytz, tzlocal, pyjsparser, js2py
  Running setup.py install for tzlocal ... done
  Running setup.py install for pyjsparser ... done
  Running setup.py install for js2py ... done
Successfully installed js2py-0.59 pyjsparser-2.5.2 pytz-2018.4 tzlocal-1.5.1

**Comment by blshkv** [comment]
@ihgazni2 I dont understand when you said "works for me". The code is clearly *NOT* python3 compatible.

I hit the same error with Js2Py-0.60.ebuild:
```
/usr/bin/python3.6 /var/tmp/portage/dev-python/Js2Py-0.60/temp/tmpw9iwaqwp.py
  File "/usr/lib64/python3.6/site-packages/js2py/internals/constructors/jsfunction.py", line 74
    print ' '.join(map(to_string, args))
            ^
SyntaxError: invalid syntax

  File "/usr/lib64/python3.6/site-packages/js2py/internals/speed.py", line 50
    print timeit(
               ^
SyntaxError: invalid syntax

  File "/usr/lib64/python3.6/site-packages/js2py/internals/byte_trans.py", line 738
    print a.declared_vars
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(a.declared_vars)?

  File "/usr/lib64/python3.6/site-packages/js2py/test_internals.py", line 9
    print seval.eval_js_vm(x)
              ^
SyntaxError: invalid syntax

removing /var/tmp/portage/dev-python/Js2Py-0.60/temp/tmpw9iwaqwp.py
writing byte-compilation script '/var/tmp/portage/dev-python/Js2Py-0.60/temp/tmpyqt0h4po.py'
/usr/bin/python3.6 /var/tmp/portage/dev-python/Js2Py-0.60/temp/tmpyqt0h4po.py
  File "/usr/lib64/python3.6/site-packages/js2py/internals/constructors/jsfunction.py", line 74
    print ' '.join(map(to_string, args))
            ^
SyntaxError: invalid syntax

  File "/usr/lib64/python3.6/site-packages/js2py/internals/speed.py", line 50
    print timeit(
               ^
SyntaxError: invalid syntax

  File "/usr/lib64/python3.6/site-packages/js2py/internals/byte_trans.py", line 738
    print a.declared_vars
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(a.declared_vars)?

  File "/usr/lib64/python3.6/site-packages/js2py/test_internals.py", line 9
    print seval.eval_js_vm(x)
              ^
SyntaxError: invalid syntax

removing /var/tmp/portage/dev-python/Js2Py-0.60/temp/tmpyqt0h4po.py
running install_egg_info
running egg_info
writing Js2Py.egg-info/PKG-INFO
writing dependency_links to Js2Py.egg-info/dependency_links.txt
writing requirements to Js2Py.egg-info/requires.txt
writing top-level names to Js2Py.egg-info/top_level.txt
reading manifest file 'Js2Py.egg-info/SOURCES.txt'
writing manifest file 'Js2Py.egg-info/SOURCES.txt'
Copying Js2Py.egg-info to /var/tmp/portage/dev-python/Js2Py-0.60/image/_python3.6/usr/lib64/python3.6/site-packages/Js2Py-0.60-py3.6.egg-info
running install_scripts
  File "/usr/lib64/python3.6/site-packages/js2py/internals/constructors/jsfunction.py", line 74
    print ' '.join(map(to_string, args))
            ^
SyntaxError: invalid syntax

  File "/usr/lib64/python3.6/site-packages/js2py/internals/speed.py", line 50
    print timeit(
               ^
SyntaxError: invalid syntax

  File "/usr/lib64/python3.6/site-packages/js2py/internals/byte_trans.py", line 738
    print a.declared_vars
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(a.declared_vars)?

  File "/usr/lib64/python3.6/site-packages/js2py/test_internals.py", line 9
    print seval.eval_js_vm(x)
              ^
SyntaxError: invalid syntax
```

Please review the source code

**Comment by blshkv** [comment]
Thanks. Please release a new version soon.
