### ISSUE TITLE
[VM] Can't use 'in' operator to search in functions

### ISSUE THREAD

**Issue by czukowski** [PiotrDabkowski/Js2Py#107]
It appears as if the new VM didn't count functions as objects.

Running this code results in _JsException: TypeError: You can't use 'in' operator to search in non-objects_

```py
seval.eval_js_vm("var a = function () {}; a.prop = true; a(); 'prop' in a;")
```

**Comment by PiotrDabkowski** [comment]
The functions are definitely objects in the new VM, its just the bug in the in_op that checks whether the first operand is an object instead of the second operand.

You can confirm that with 

    new String('prop') in a 

This will work ;)

**Comment by czukowski** [comment]
I see, thanks for clarifying, although I'm afraid I wouldn't have that luxury if I ran a JS code that I didn't "own" (ie from a web page).

In any case, thanks for coming up with the VM, it looks really promising.
