### ISSUE TITLE
[VM] Subtracting from object properties

### ISSUE THREAD

**Issue by czukowski** [PiotrDabkowski/Js2Py#114]
Found a tricky one :)

This one works fine:

```py
eval('''var v=44; v-=12; throw v;''')  # throws 36
```

And this one does not:

```py
eval('''var o={p: 44}; o.p-=12; throw o.p;''')  # throws -36
```

After quite some head scratching I managed to find that the arguments are reversed in [sub_op function](https://github.com/PiotrDabkowski/Js2Py/blob/b1bbbeb0bcfef6f9548217f51caa4545545de550/js2py/internals/operations.py#L113) in the 2nd case. That has brought me to [STORE_MEMBER_OP](https://github.com/PiotrDabkowski/Js2Py/blob/b1bbbeb0bcfef6f9548217f51caa4545545de550/js2py/internals/opcodes.py#L421) where `value` and `get_member(left, name, ctx.space)` might need swapping (and perhaps once more three lines just above), but I'm totally guessing on this one.

If that's correct, I can provide a pull request with a fix if you like.

**Comment by PiotrDabkowski** [comment]
Yeah that's the reason, nice catch haha

This should be swapped in 4 places in total, 2 in `STORE_MEMBER_OP` and 2 in `STORE_MEMBER_DOT_OP`. 

By the way, you can use log or console.log for printing instead of throw :)

**Comment by czukowski** [comment]
Yes, I've noticed your addition of console.log, thank you. It comes very handy in case of debugging larger portions of JavaScript code.
