### ISSUE TITLE
Apparent bug or problem

### ISSUE THREAD

**Issue by timweb** [PiotrDabkowski/Js2Py#12]
I am having problems getting this js code https://gist.github.com/kekscom/10925007 to run properly in Python using Js2Py.  It might possibly be a character array vs string vs unicode issue.

It does run fine in js - as seen in this fiddle:  http://jsfiddle.net/7Laut8gq/1/

__Thank you for taking a look at this, and let me know if I can support your efforts.__

--- This is my python code:

import sys, glob, os, js2py
javascript_function = open("fJson.js").read()
jsTryToFix = js2py.eval_js(javascript_function)
json_data_raw = open(filename_to_fix).read()
json_data_fixed = jsTryToFix(json_data_raw)

------

In the javascript - in my local file version of the fixJson(stuff) in http://jsfiddle.net/7Laut8gq/1/ -right before the return, I placed
   console.log(json);
But it prints empty; it works fine for a "Test string".
 json_data_fixed returns empty; but if change the javascript_function to return "Test string",
 it returns as expected in json_data_fixed

**Comment by PiotrDabkowski** [comment]
Thank you. I think I found a problem. Try changing line 531 of translators/pyjsparser.py file to:     

                        st += '\\' + ch  # DONT ESCAPE!!!    

and let me know if it works :)
 I will upload next version of Js2Py tomorrow with few fixes.
