### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by Xmmie** [PiotrDabkowski/Js2Py#126]
I am trying to parse a number of JavaScript codes into AST, the code is from a dataset and it might have syntax error.

Is there away i can use tolerant mode in Js2Py?

Thank you.

**Comment by PiotrDabkowski** [comment]
Try this:

```python
import js2py
esprima = js2py.require('esprima')
esprima.parseScript('"use strict"; with (x) {}', { "tolerant": True })
```
