### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by timweb** [PiotrDabkowski/Js2Py#13]
This is a secondary issue.  If there's a file ending in

,"created_at":"2015-07-11 22:45:53"},{

Your fixer will cure the problem and place any {}[] characters as needed for completion.

However, if in the above example the file ends in

,"creat

The closing quote will be placed, however the value part of the  __key : value__ pair will be missing, and prevent json from parsing.

My temporary suggested fix is to iterate through your fixer, removing the last character until I get the fixed json to validate; but perhaps there's a better method.

**Comment by PiotrDabkowski** [comment]
I don't understand the problem. Is it a problem with Js2Py or with JavaScript fixer code used? Js2Py should output exactly what V8 does.
