### ISSUE TITLE
About use js2py to call or get python context

### ISSUE THREAD

**Issue by xnchall** [PiotrDabkowski/Js2Py#131]
I could use js2py to execute js code and get js context. Now i want to get python Object and Context data in js code, this makes me depressed, thx  :)

**Comment by xnchall** [comment]
@PiotrDabkowski  excuse me,  could you help me, thx

**Comment by PiotrDabkowski** [comment]
Hey, everything is in README.
For example to use `os` module from js.

```python
import os
import js2py

ctx = js2py.EvalJs({'os': os})
ctx.eval('console.log(os.getcwd())')
```

**Comment by xnchall** [comment]
thank u, I've read README, and known your example. Maybe i didn't make it clear. Could I say it again?
python get js object and context, temp.js is:
`var db_user_name = ''
var db_password = ''
var port = ''
var host = ''
var service_name = ''

if(1 < 2){
    db_password = 'aa'
    db_user_name = 'bb'
    host = 'localhost'
    port = '8888'
    service_name = 'orcl'
}`

python code, test.py is:
`import js2py
js_file = js2py.run_file(r'D:.....\temp.js')
print(js_file[1].db_user_name)
print(js_file[1].db_password)
print(js_file[1].host)
print(js_file[1].port)
print(js_file[1].service_name)

data = "hello world"

`
i want to get python object or context in js. That is, how to get variables "data" from test.py in temp.js, because i want to use variables 'data' from temp.py to do something
