### ISSUE TITLE
+= and -= treated as =

### ISSUE THREAD

**Issue by svalgaard** [PiotrDabkowski/Js2Py#134]
When python is added to the js context, js2py seems to ignore `+=` and` -=` and treats this as `=`. See example below.

```
import js2py

class Foo:
    def __init__(self, bar):
        self.bar = bar

context = js2py.EvalJs({'foo': Foo(5)})

context.execute('foo.bar = 10')
print(context.foo.bar)  # prints 10

context.execute('foo.bar += 15')
print(context.foo.bar)  # prints 15 expected 25

context.execute('foo.bar -= 2')
print(context.foo.bar)  # prints 2 expected 23
```

Is this a known issue? And is there a way to circumvent this?

**Comment by PiotrDabkowski** [comment]
Hey, yes it looks like a bug. You can check the PyObjectWrapper class if it handles this operstion properly. I will try to fix it today evening

**Comment by svalgaard** [comment]
I've tried wrapping Foo in PyObjectWrapper,
```
context = js2py.EvalJs({'foo': js2py.base.PyObjectWrapper(Foo(5))})
```
but this gives the same result as above.

**Comment by PiotrDabkowski** [comment]
It is wrapped automatically anyway. What I meant: probably PyObjectWrapper does not support this operation properly and hence the invalid results... I did not have a time to look into this yet, sorry!

**Comment by PiotrDabkowski** [comment]
Ok I have fixed the issue, should work fine now.

**Comment by svalgaard** [comment]
I've just tested with my larger, real javascript input and it also works. Thanks!
