### ISSUE TITLE
Reading and Appending to Js Array from Python

### ISSUE THREAD

**Issue by Ipv6Python** [PiotrDabkowski/Js2Py#138]
I'm working too read, append and remove data to an Array in Js file using Python3 with Js2Py, where there is no accurate documentation found. I tried multiple other python libraries but didn't find anything that is maintained in 2018 for this job.  My roadblock is. 

I've got a js file stored on the desktop (for now) contains below js example formatted code. 

Function SampleMethod (a, b)
{
var array = ["ab", "cd",...]
var array_1 = ["ef","gh",...]
.....
.....
.....
}

I tired in Python3 below:  

import js2py
context = js2py.get_file_contents("../Desktop/file.js")
print(context.array[])

While I'm doing get_file_contents(), the entire file is "context" is stored as "str" and not able to ready the Array and Error'd AttributeError: 'str' object has no attribute Array

What I want to do in Python3:

I want to read the Js file var inside the function and look for the specific Array value if exist's do nothing, if not append or remove value from the Array.

Is this possible or Should I move in a different direction? 
Is there a Python library than Js2Py that is maintained?

**Comment by PiotrDabkowski** [comment]
The name of the function is get_file_contents and as the name suggests it returns the **contents** of the file (string). You should `execute` the contents first inside the JS context:

```python
import js2py
context = js2py.EvalJs()
context.execute(js2py.get_file_contents("../Desktop/file.js"))
print(context.array[])
```

**Comment by Ipv6Python** [comment]
When I tried the above it throws an Makerror with undefined array..  I can confirm the Array is defined and used. 


raise MakeError('ReferenceError', '%s is not defined' % prop)
js2py.internals.simplex.JsException: ReferenceError: Array is not defined

**Comment by PiotrDabkowski** [comment]
This is because the variable array is inside of the function. Js2Py is a relatively advanced library and may be hard to start with if you have little prior programming experience.

```python
import js2py
context = js2py.EvalJs()
context.execute("var array = [1,2,3]")
print(context.array)
```

Will work just fine.

**Comment by Ipv6Python** [comment]
I want to load from the file without hard-coding the Array.  

Certainly, js2py advanced and is helping me with my use case but didn't find any documentation of functions or classes available. Is there any documentation that has detail explanation?
