### ISSUE TITLE
What would be the equivalent of esprima's { comment: true } flag in pyesprima?

### ISSUE THREAD

**Issue by feifang24** [PiotrDabkowski/Js2Py#143]
Hi! First of all, thank you so much for your pyesprima parser! However, I'm most likely missing something here, but I couldn't seem to find a way to set the pyesprima equivalent of { comment: true } flag to collect comments in pyesprima.

Any pointer would be greatly appreciated! Thanks again!

**Comment by PiotrDabkowski** [comment]
Unfortunately, pyesprima does not support comments. You can try the automated translation of esprima via js2py which is equivalent to the esprima js library.

```python
>>> import js2py
>>> esprima = js2py.require("esprima")
>>> ast = esprima.parse("var a = 5 // some comment \n /* another comment */", {"comment": True}).to_dict()
>>> from pprint import pprint
>>> pprint(ast)
{u'body': [{u'declarations': [{u'id': {u'name': 'a',
                                       u'type': u'Identifier'},
                               u'init': {u'raw': '5',
                                         u'type': u'Literal',
                                         u'value': 5},
                               u'type': u'VariableDeclarator'}],
            u'kind': u'var',
            u'type': u'VariableDeclaration'}],
 u'comments': [{u'type': u'Line', u'value': ' some comment '},
               {u'type': u'Block', u'value': ' another comment '}],
 u'sourceType': u'script',
 u'type': u'Program'}
```

The only downside is that the auto-translated esprima is about 20 times slower than the manually translated esprima. The auto-translated code can be found in the examples as well (https://github.com/PiotrDabkowski/Js2Py/blob/master/examples/pyesprima.py).
