### ISSUE TITLE
Code to handle backspace character breaks \b in regex patterns

### ISSUE THREAD

**Issue by worstperson** [PiotrDabkowski/Js2Py#15]
Here is my test for it:

import js2py
t = r"function test() {return 'failed!'.replace(new RegExp('failed\\\\b','g'), 'passed!')}"
print js2py.eval_js(t)()

Commenting out lines 517 and 518 in pyjsparser.py seems to fix the issue, it's not a proper fix though.

**Comment by PiotrDabkowski** [comment]
Only \b was causing the problem \v \n and unicode escapes work fine. I did comment out these lines and now it works fine. The bug was due to differences between python and js regex. Thank you for pointing it out!
