### ISSUE TITLE
Is it support multi lines codes？

### ISSUE THREAD

**Issue by youyiqin** [PiotrDabkowski/Js2Py#153]
```python
# code
jscode = """
var a = 1
var b = 2
var bar = function (a){return a}
"""
test = js2py.eval_js(jscode)
print(test)
print(test.a)

# output:
'function (a) { [python code] }'
None
```

I need : test.a is 1
thanks.

**Comment by youyiqin** [comment]
@PiotrDabkowski

**Comment by SeaHOH** [comment]
Read more examples.

**Comment by PiotrDabkowski** [comment]
Well said, read the examples. This example from readme even use the same variable name:

# Adding Python built-in sum to the JS context:
>>> context = js2py.EvalJs({'python_sum': sum})  
>>> js_code = '''
var a = 10
function f(x) {return x*x}
'''
>>> context.execute(js_code)
# Get value of variable a:
>>> context.a
10
