### ISSUE TITLE
Publish a new release

### ISSUE THREAD

**Issue by pro-src** [PiotrDabkowski/Js2Py#162]
Please.

**Comment by PiotrDabkowski** [comment]
Not sure what you mean by release, I published  v0.61 to pip.

**Comment by pro-src** [comment]
Ah, you haven't seen my other comments yet. v0.62 is on pypi btw. I'll grab a link for those comments. What I mean by a new release, is a release that includes the fix from my PR.

**Comment by pro-src** [comment]
https://github.com/PiotrDabkowski/Js2Py/commit/f6be867f1d1bd8b9f84d4de4812f91c123a227e5#r33251030

**Comment by PiotrDabkowski** [comment]
v0.62 should be fine minus these minor fixes that are still pending:

```python
>>> js2py.eval_js('1e21+""')
'1e+21'
```

**Comment by pro-src** [comment]
Thank you!
