### ISSUE TITLE
Unused imports

### ISSUE THREAD

**Issue by pro-src** [PiotrDabkowski/Js2Py#167]
https://github.com/PiotrDabkowski/Js2Py/blob/b5fbaafddf41f4efc1a4841a8a35f2fda094e60a/js2py/base.py#L8

**Comment by PiotrDabkowski** [comment]
Thanks, but this is not the biggest problem: 
https://codeclimate.com/github/PiotrDabkowski/Js2Py/code

:) I currently only fix critical issues / bugs as I have some other interesting projects going on. I guess there is no much point fixing all these code style issues as I am basically the only maintainer.

**Comment by pro-src** [comment]
Closing valid issues is not the way to attract maintainers.

Take a look at this issue for a contrast: https://github.com/webtorrent/webtorrent-desktop/issues/1571 
Can you believe that it's open??? But hey at least they don't close valid issues...

The correct response would have been: ***I will accept a PR for this and if you see any other issues, PRs welcome***

How else is somebody supposed to establish trust so they might become collaborators?
I am a past contributor and I find the dismissal as disrespectful so don't expect future PRs from me. Furthermore, I told you when you broke my damn PR and released it. Smart guy.

**Comment by pro-src** [comment]
Oh... , That's right, you left those there when you broke my PR and I had to go and tell you to fix it.... So, you're butt hurt and wanna close this issue? Really... Just WOW....

**Comment by pro-src** [comment]
Honestly though, what really gets me is that it shouldn't have taken you any longer to fix your screw up then it took for you to comment on this issue. It's pathetic.

**Comment by pro-src** [comment]
@VeNoMouS you really want to keep using this guy's code? It's crap. It's going to stay crap.

**Comment by PiotrDabkowski** [comment]
? There was no offence intended. PRs are of course always welcome, but sorry, a few unused imports are not a big problem and as I said, I currently only fix critical issues. Given the issue is not critical it was closed, simple as this. Code style is the least concern that does not bother anybody.
If you have some specific examples where Js2Py does not work please raise the issue.

**Comment by pro-src** [comment]
I won't be commenting further because I fear you that you might have another outburst (#168) but before I go, I want to leave you with a thought. How critical are the other open issues? How obvious is that to anybody who might be watching? Good luck with your project.
