### ISSUE TITLE
Stop lying about full support for ECMAScript 5.1

### ISSUE THREAD

**Issue by pro-src** [PiotrDabkowski/Js2Py#168]

**Comment by PiotrDabkowski** [comment]
Sorry about closing your unused import issue, but really, I find this kind of strange and kind of offending. If you have some specific examples, please raise a separate issue. There are indeed some edge cases where it may fail (like with the number to string conversion), but overall you can run pretty much any Js code, eg see babel.js translated to python: https://github.com/PiotrDabkowski/Js2Py/blob/master/js2py/es6/babel.py

**Comment by pro-src** [comment]
It's not strange you just said yourself...

> There are edge cases? Yes.

How many? More than a few.
How spec compliant is js2py? It's not spec compliant.
Does it have full support for EcmaScript 5? ***No***

*Stop lying*

Regarding unused imports. You closed a valid issue so I opened another valid issue to see what you would do. You lack integrity.

**Comment by pro-src** [comment]
![stackoverflow com_users_1354439_piotr-dabkowski](https://user-images.githubusercontent.com/34285059/57180766-a3bd2880-6e51-11e9-9d39-766e7c8cb22c.png)

**Comment by PiotrDabkowski** [comment]
Ehh pretty childlish. In the simple terms, just fuck off and do it yourself man. Will not tolerate such attitude.

**Comment by pro-src** [comment]
There we go, I see you now.

**Comment by pro-src** [comment]
The README.md is fraudulent in a lot of way. Let's pick one.
> Please let me know if you find any bugs - they will be fixed within 48 hours.

From two years ago (It alone proves my point): https://github.com/PiotrDabkowski/Js2Py/issues/42

In those two years(probably longer), you never updated the README.md to reflect the actual project status.

But the truth is (and *it's crystal clear* because of the code, even more clear than your last comment) you always knew that it wasn't a full implementation, you always knew there wasn't full support. Thus the title, whether you find it offensive or not, is completely accurate. 

But hey man, I'm sorry for being accurate so let's be inaccurate, shall we?
You got you're MPhil degree through the baloney process... Wait that's strange... Now I remember...., you actually got you're McPhil degree from McDonald's. :laughing: And what's with the disfigured sheep on your projects page? :confused:

On second thought, keep calling it a full implementation instead of testing for compliance: https://github.com/tc39/test262

I understand that you need it. I'm sorry for doubting that.
