### ISSUE TITLE
python 2.7.5  ... SyntaxError: unqualified exec is not allowed in function '__init__' it contains a nested function with free variables (evaljs.py, line 155)

### ISSUE THREAD

**Issue by Chingliu** [PiotrDabkowski/Js2Py#193]

**Comment by Chingliu** [comment]
I tried this, then it pass python -m compileall:


    def __initialize(self):
        self.__dict__['_context'] = {}
        exec (DEFAULT_HEADER, self._context)
    
    def __init__(self, context={}, enable_require=False):
        self.__initialize()
        self.__dict__['_var'] = self._context['var'].to_python()

        if enable_require:
            def _js_require_impl(npm_module_name):
                from .node_import import require
                from .base import to_python
                return require(to_python(npm_module_name), context=self._context)
            setattr(self._var, 'require', _js_require_impl)

        if not isinstance(context, dict):
            try:
                context = context.__dict__
            except:
                raise TypeError(
                    'context has to be either a dict or have __dict__ attr')
        for k, v in six.iteritems(context):
            setattr(self._var, k, v)

**Comment by 1271** [comment]
> Being the last of the 2.x series, 2.7 received bugfix support until 2020. Support officially stopped January 1 2020, and 2.7.18 code freeze occurred on January 1 2020, but the final release will occur after that date.

https://www.python.org/dev/peps/pep-0373/

Try using 3.8. He is cool! :+1:
