### ISSUE TITLE
Arrow function not supported in ECMA 5.1

### ISSUE THREAD

**Issue by dmintercept** [PiotrDabkowski/Js2Py#199]
Is there a way around this?

**Comment by jennasisis** [comment]
Just replace the arrow functions with normal functions

**Comment by PiotrDabkowski** [comment]
You can always compile JS6 to JS5 with things like babel.
In fact you have js2py.eval_js6 which does support JS6 and arrow functions. Under the hood it calls babel.js which was [translated to python](https://github.com/PiotrDabkowski/Js2Py/blob/master/js2py/es6/babel.py) to translate JS6 -> JS5 and then calls Js2Py to do JS5 -> Python.

**Comment by dmintercept** [comment]
Yeah I think babel is what I'm looking for.  The flow would be get source code for the npm package i want, add bable to the build, re-build a js6 package calling babel to make it js5 compatible, and finally translate it to python with js2py
