### ISSUE TITLE
FFI bridge

### ISSUE THREAD

**Issue by jordwalke** [PiotrDabkowski/Js2Py#2]
Hello, is there an example of using functions defined elsewhere in Python? In my example, I'd like a very simple way to call into python libraries for the sake of writing Vim plugins.

For the longest time, developers were locked into using VimScript or Python to build Vim plugins. But with this project, it is theoretically possible for people to use virtually *any* language (that compiles to JS - so basically all of them) in order to write Vim plugins (or Sublime plugins!)

**Comment by PiotrDabkowski** [comment]
It should work now. Just use pyimport statement that I added today. See example in readme and let me know how it works :) Also I would have to spend about 70 more hours on this project to make it perfect and reliable. Unfortunately I don't have time for that and I don't know whether it's worth to spend 70 hours on a project used by less than 100 people.

**Comment by jordwalke** [comment]
Well, thank you.
