### ISSUE TITLE
Copying of context into _var prevents the use of more complex browser context objects

### ISSUE THREAD

**Issue by fake-name** [PiotrDabkowski/Js2Py#201]
Basically, I'm trying to stub out enough of a browser DOM and associated functionality to run some JS from the web.

I implemented most of this as a complex class that looks like a dict to pass through as the context object to `EvalJs()`, but it turns out that doesn't work since it seems `EvalJs()` copies everything in the passed context into it's internal `_var` member. 

Is there a reason for this copy? It'd be nice if instead the lookup operations just kept the context parameter around, and used it directly when objects aren't overridden.

I can put together a PR for this if it's something you're open to.

**Comment by PiotrDabkowski** [comment]
I am not sure I understand - what does not work?  `_var` is just a python view of the JS context. You can add python objects to it and then it handles  `JS context Call ->Python Method -> JS context Return` for you including parameter conversion etc. Alternatively you can implement a `native`JS class via prototype and constructor, such as for Array: [prototype](https://github.com/PiotrDabkowski/Js2Py/blob/master/js2py/prototypes/jsarray.py), [constructor](https://github.com/PiotrDabkowski/Js2Py/blob/master/js2py/constructors/jsarray.py). But this is a bit more involved. 
You can prepare a PR, it could make the problem easier to understand.

**Comment by fake-name** [comment]
Effectively, what I'm trying to accomplish is have global accesses try to fetch from the object I pass in as the `context` parameter to `EvalJs()`. 

Right now, the context object is an instance of a custom class that overrides the various `__getattr__()`, `__contains__()`, `__setattr__()` members so it acts like a dict, but does additional things on member get/set operations.

This doesn't work, since right now the context parameter is iterated over to copy it into the `_var` dict.

Really, I think this may not be possible, since the `_var` dict is passed to `exec()`, and you cannot pass non-dict objects to `exec()`, even if they present a dict-like interface.

**Comment by PiotrDabkowski** [comment]
Can you create a PR with this or provide a minimal code sample? It would be much easier to understand the issue.

**Comment by fake-name** [comment]
Probably not, since it seems what I want isn't possible. Sorry.

**Comment by PiotrDabkowski** [comment]
Well, everything is possible :) And a DOM implementation is an interesting project.

**Comment by fake-name** [comment]
Well, not possible without custom compiling python, at least.
