### ISSUE TITLE
AssertionError: Error when converting module to the js bundle

### ISSUE THREAD

**Issue by Z-Q-Yang** [PiotrDabkowski/Js2Py#207]
It seems that js2py can not be successfully applied to all kinds of npm package.
In more complex situations, while using typescript-eslint-parser to generating AST for typescript, 
just run the simple demo code:
      ts_parser = js2py.require('typescript-eslint-parser')

The assert declaration in node_import.py goes wrong:
Traceback (most recent call last):
  File "D:/pyspace/Lab_js2py/js2py_esprima.py", line 23, in <module>
    ts = js2py.require('typescript-eslint-parser')
  File "D:\Anaconda3\lib\site-packages\js2py\node_import.py", line 150, in require
    maybe_version_str=maybe_version)
  File "D:\Anaconda3\lib\site-packages\js2py\node_import.py", line 102, in _get_and_translate_npm_module
    ) == 0, 'Error when converting module to the js bundle'
AssertionError: Error when converting module to the js bundle

however, when running "npm install typescript-eslint-parser", it succeed. I cannot figure out how is that, code in the assert declaration seems not so easy to understand.

**Comment by PiotrDabkowski** [comment]
It seems like some bad module. Try:
`npm install typescript-eslint-parser` and then in node:
```
> require("typescript-eslint-parser")
Thrown:
{ Error: Cannot find module 'typescript' ...
```
you basically see the exact same error in js2py above the assertion error, read the output carefully.

`js2py.require('typescript-eslint')` works as expected and simply prints "Nothing to see yet..." the same result is in Node.js.
Not sure how to install and import this library properly, check the documentation.

**Comment by egebuyukdura** [comment]
I don't know if it's okay to revive a closed issue after a year or so within the GitHub community (first time commenting on something). But I have found myself in a similar situation as above where my module is the 'web3' JavaScript module. I am getting the following error if I try to convert the module to python:

`web3JS = js2py.require('web3')`

The output is:

```
File "C:\Users\***\venv\lib\site-packages\js2py\node_import.py", line 155, in require
    py_code = _get_and_translate_npm_module(module_name, include_polyfill=include_polyfill, update=update,
  File "C:\Users\***\venv\lib\site-packages\js2py\node_import.py", line 77, in _get_and_translate_npm_module
    _init()
  File "C:\Users\***\venv\lib\site-packages\js2py\node_import.py", line 23, in _init
    assert subprocess.call(
AssertionError: Could not link required node_modules
```

And when I change my node_import.py file to the one in this issue (https://github.com/PiotrDabkowski/Js2Py/issues/125), as suggested by @hellmolt, I get the following error:


```
assert subprocess.call(
AssertionError: Error when converting module to the js bundle
```

I was able to npm install the said module and use it with Node.js using import. I have also installed the web3 module globally so I'm kind of stuck.

**Comment by TheSwede86** [comment]
> I don't know if it's okay to revive a closed issue after a year or so within the GitHub community (first time commenting on something). But I have found myself in a similar situation as above where my module is the 'web3' JavaScript module. I am getting the following error if I try to convert the module to python:
> 
> `web3JS = js2py.require('web3')`
> 
> The output is:
> 
> ```
> File "C:\Users\***\venv\lib\site-packages\js2py\node_import.py", line 155, in require
>     py_code = _get_and_translate_npm_module(module_name, include_polyfill=include_polyfill, update=update,
>   File "C:\Users\***\venv\lib\site-packages\js2py\node_import.py", line 77, in _get_and_translate_npm_module
>     _init()
>   File "C:\Users\***\venv\lib\site-packages\js2py\node_import.py", line 23, in _init
>     assert subprocess.call(
> AssertionError: Could not link required node_modules
> ```
> 
> And when I change my node_import.py file to the one in this issue (#125), as suggested by @hellmolt, I get the following error:
> 
> ```
> assert subprocess.call(
> AssertionError: Error when converting module to the js bundle
> ```
> 
> I was able to npm install the said module and use it with Node.js using import. I have also installed the web3 module globally so I'm kind of stuck.

I am new to Python programming and Node.js but recently installed "js2py" on Windows 11 and received the same error;
`AssertionError: Could not link required node_modules`

However as @egebuyukdura said the solution posted by @hellmolt  in #125 here:
https://github.com/PiotrDabkowski/Js2Py/issues/125#issuecomment-958189688
solves it.

I saw that he (@hellmolt) did a PR #274 (if the link does not work it is [here](https://github.com/PiotrDabkowski/Js2Py/pull/274)) which apparently caused "js2py" to fail on MacOS and Linux and guessing that's why it isn't merged?
