### ISSUE TITLE
js2py.internals.simplex.JsException

### ISSUE THREAD

**Issue by SLey3** [PiotrDabkowski/Js2Py#210]
Hi there,
When I ran a class I created which uses the `translate_file()` function, I got this error:
```
Traceback (most recent call last):
  File "c:/Users/ghub4/AppData/Local/Programs/Portal Password Manager/src/appResources/resources/web/webRequests.py", line 67, in <module>
    webRequest('gmail.com', 'test@gmail.com', 'Test_password', login_page=True)
  File "c:/Users/ghub4/AppData/Local/Programs/Portal Password Manager/src/appResources/resources/web/webRequests.py", line 50, in __init__
    self.parse
  File "c:/Users/ghub4/AppData/Local/Programs/Portal Password Manager/src/appResources/resources/web/webRequests.py", line 56, in parse
    import scraper as Scrape
  File "c:\Users\ghub4\AppData\Local\Programs\Portal Password Manager\src\appResources\resources\web\scraper.py", line 29, in <module>
    var.get('exports').put('__esModule', Js(True))
  File "C:\Users\ghub4\.virtualenvs\Portal_Password_Manager-BXsPVI-_\lib\site-packages\js2py\base.py", line 1158, in get
    raise MakeError('ReferenceError', '%s is not defined' % prop)
js2py.internals.simplex.JsException: ReferenceError: exports is not defined
```
I think it may or may not be because of a thing I missed or if theres something wrong with the `translate_file()` function.
This is the piece of code that uses that function:
```python
try:
        import scraper as Scrape
       except ImportError:
        js2py.translate_file(JS_FILEPATH, 'scraper.py')
        SCRAPER_PATH = os.path.join(os.path.expanduser(os.getenv('USERPROFILE')) + '\\AppData\\Local\\Programs\\Portal Password Manager\\', 'scraper.py')
        FINAL_PATH = os.path.expanduser(os.getenv('USERPROFILE')) + '\\AppData\\Local\\Programs\\Portal Password Manager\\src\\appResources\\resources\\web'
        shutil.move(SCRAPER_PATH, FINAL_PATH, copy_function=shutil.copytree)
        import scraper as Scrape
```
(_If you need to see the code for the scraper.py file, just tell me._)
How this problem be fixed?

**Comment by worstperson** [comment]
You can see the error in the log - "scraper.py", line 29: 
`var.get('exports').put('__esModule', Js(True))`

Seems to be this:
`Object.defineProperty(exports, "__esModule", { value: true });`
a line generated by NodeJS for CommonJS module afaict.

So you'd need to import CommonJS (or stub) into your context or cut that and dependent code from your project.

**Comment by SLey3** [comment]
> You can see the error in the log - "scraper.py", line 29:
> `var.get('exports').put('__esModule', Js(True))`
> 
> Seems to be this:
> `Object.defineProperty(exports, "__esModule", { value: true });`
> a line generated by NodeJS for CommonJS module afaict.
> 
> So you'd need to import CommonJS (or stub) into your context or cut that and dependent code from your project.

What file or code would be the context? Also the js file doesn't have `Object.defineProperty(exports, "__esModule", { value: true });`, it has: `exports.__esModule = true;`.@worstperson

**Comment by worstperson** [comment]
Context is just the execution environment. Easiest approach would be to just insert the dependency code before yours, or alternatively, translating the dependency and loading it before it's referenced should work.

**Comment by SLey3** [comment]
What if the js file is being compilied from a typescript file and I tried inserting the dependency code before mine and still getting the same error. I also tried importing commonJs but the IDE doesn't recognize the module and gives me errors when I try to import it.

**Comment by SLey3** [comment]
clos
