### ISSUE TITLE
How to convert to more readable python code？

### ISSUE THREAD

**Issue by Baloneo** [PiotrDabkowski/Js2Py#224]
foo.js
```
var a;
for (a=0; a < 3; a ++ ) {
   console.log("hello")
}
```
I want like this:
```
a = None
for a in range(3):
    print("hello")
```

**Comment by PiotrDabkowski** [comment]
Such nice code cannot be generated for multiple of reasons, if the goal is to be able to execute any javascript code. For the simple case like above, yes it works. But for something even as simple as addition, we need a custom operation if we want it to work in all the cases. For example, in Javascript this will print "4hello":

```
a = 4
b = "hello"
console.log(a + b)
```
while in Python `a + b` is an error, cant add string and float. Hence, we cannot simply write `a + b` if we use primitive python types (str and float). We would either need a custom class for integer and string (`a = Js(4)` as is done in Js2Py), or write addition as say `js2py_sum(a, b)`. You can see this already hurts readability. This is just one example, there are also scoping issues, and much more, the net effect of all these complications is that the Js2Py generated code is ugly.

You can make a module that generates a simple code, but it will not work in all the cases. If you want to give it a try, see how translation is done in Js2Py:
https://github.com/PiotrDabkowski/Js2Py/blob/master/js2py/translators/translating_nodes.py#L349

**Comment by Baloneo** [comment]
Thans!
