### ISSUE TITLE
Date.now().toString(36) returns wrong result

### ISSUE THREAD

**Issue by TranDatDT** [PiotrDabkowski/Js2Py#228]
Hello friend,
I found that `js2py.eval_js("Date.now().toString(36)")` returns `Mon Nov 16 2020 16:11:47 GMT+0700 (+07)` instead of a string in base36.

**Comment by PiotrDabkowski** [comment]
This is not a part of specification: https://www.ecma-international.org/ecma-262/11.0/index.html#sec-date.prototype.tostring
