### ISSUE TITLE
Question about improving performance

### ISSUE THREAD

**Issue by mozrat** [PiotrDabkowski/Js2Py#27]
Hello,

I'm enjoying using Js2Py but I'm finding it slow, especially when I start to load large Javascript libraries into the context. Unfortunately some of the work I am doing has to be synchronous and the delay is noticeable

Would it be possible to cache (or return) the translated code to avoid the penalty of translating just before  I need to execute it?

Thanks

**Comment by PiotrDabkowski** [comment]
You can get translated code using js2py.translate_js(js_code)

**Comment by mozrat** [comment]
I've had to extend js2py a little to do what I am aiming for, which is to avoid the penalty of Just in time conversion of JS to Python.

```
class MyEvalJs(js2py.EvalJs):
    def execute_py(self, py_code):
        exec py_code in self._context
```

And then in the various places that I am fetching my translated code I am executing like this

```
    def run(self, rule):
        ctxt = MyEvalJs(self.ctxt)
        py_code = rule.translated_script
        result = ctxt.execute_py(py_code)
```

This project has really helped me out - thank you very much
