### ISSUE TITLE
Possible to disable "pyimport"

### ISSUE THREAD

**Issue by zeroSteiner** [PiotrDabkowski/Js2Py#29]
I have a quick question regarding this project, it looks great by the way. My question is two fold, first is it possible to disable the pyimport statement? Secondly, if it is possible, to your knowledge would this effectively create an execution sandbox that would be suitable for running untrusted code? Thanks!

**Comment by PiotrDabkowski** [comment]
You can remove the pyimport statement by removing it from the parser (https://github.com/PiotrDabkowski/Js2Py/blob/master/js2py/translators/pyjsparser.py) just remove  these 2 lines:

    elif val == 'pyimport':   # <<<<< MODIFIED HERE
                return self.parsePyimportStatement()

Whether that would make a safe sandbox I can't tell for sure. The js2py does not import or expose any unsafe operation. If it was the interpreter then I would be pretty sure it's safe. However it translates the code to python and there may be a bug in translation that results in unsafe code. I doubt it is possible but I can't guarantee.

**Comment by zeroSteiner** [comment]
Thanks for the response, I'll look into a bit more.

**Comment by vsvad** [comment]
**Thanks** for help!
