### ISSUE TITLE
js2py can't understan **of**

### ISSUE THREAD

**Issue by Ella16** [PiotrDabkowski/Js2Py#307]
js2py can't understan for loop **of**

### code 
```
import js2py

tmp_js = 'for (var a of [1,2,3,4]){ \
     console.log(a) \
     } \
    '
eval_res, tempfile = js2py.eval_js(tmp_js)
```

### error msg
> Exception has occurred: JsException
> SyntaxError: Line 1: Unexpected identifier

when i print the problematic token from throwUnexpectedToken
it shows,
`{'type': 3, 'value': 'of', 'raw': 'of', 'lineNumber': 1, 'lineStart': 0, 'start': 11, 'end': 13}
`

**Comment by worstperson** [comment]
for...of is an es6 feature
```
import js2py

tmp_js = 'for (var a of [1,2,3,4]){ \
     console.log(a) \
     } \
    '
js2py.eval_js6(tmp_js)
```
Better to convert it to es5 if possible, babel adds a lot of overhead.
