### ISSUE TITLE
 JavaScript 6 Support

### ISSUE THREAD

**Issue by JAlbertCode** [PiotrDabkowski/Js2Py#308]
Is there any way to use translate_file function or run_file function with Javascript 6?

**Comment by worstperson** [comment]
I only gave this a minimal test, but it seems to work.
```
import os
import js2py

def translate_file6(input_path, output_path):
    js = js2py.get_file_contents(input_path)
    py_code = js2py.translate_js6(js)
    lib_name = os.path.basename(output_path).split('.')[0]
    head = '__all__ = [%s]\n\n# Don\'t look below, you will not understand this Python code :) I don\'t.\n\n' % repr(
        lib_name)
    tail = '\n\n# Add lib to the module scope\n%s = var.to_python()' % lib_name
    out = head + py_code + tail
    js2py.write_file_contents(output_path, out)

translate_file6('js6test.js', 'js6test.py')
```
Try importing babel first if you have issues running the resulting python file.
`import js2py.es6.babel`

**Comment by JAlbertCode** [comment]
Thanks for the code and suggestion. I tried running it but the terminal was stuck on initializing babel for over 20 minutes. I'm going to look for an alternative solution.

**Comment by milahu** [comment]
see also

- [quadramadery/js2py](https://github.com/quadramadery/js2py) based on espree parser, written in javascript
- [7HR4IZ3/es62py](https://github.com/7HR4IZ3/es62py) based on esprima parser and js2py library, written in python
