### ISSUE TITLE
AttributeError: PyJsNumber instance has no attribute '__trunc__'

### ISSUE THREAD

**Issue by Jake7zDunn** [PiotrDabkowski/Js2Py#4]
I am trying to use this (http://pastebin.com/30stpGzM) script with Js2Py but I get this traceback:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "requests\sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "requests\sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "requests\sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "scraper.py", line 26, in send
    return self.solve_cf_challenge(resp, request.headers, resp.cookies, **kwargs)
  File "scraper.py", line 69, in solve_cf_challenge
    answer = str(int(js2py.eval_js(js)) + len(domain))
AttributeError: PyJsNumber instance has no attribute '__trunc__'
```
The value in js variable is:
```javascript
var t,r,a,f, XbMvhKS={"mKW":+(String(1+1+1+1+0)+String(1+1+1+1+1+1+1+1))};        ;XbMvhKS.mKW+=+(String(1+1+1+0)+String(1+1+1+1));XbMvhKS.mKW+=+(String(+1+0)+String(1+1+1+1+1+1+1));XbMvhKS.mKW*=+(String(1+1+1+1+1+0)+String(+0));XbMvhKS.mKW+=+(String(1+1+0)+String(1+1+1)); parseInt(XbMvhKS.mKW, 10)
```
I don't understand the problem because if I use js2py.eval_js(js) manually in console with the same js code works perfectly

**Comment by PiotrDabkowski** [comment]
The value returned by eval_js is a PyJsNumber type (you can see that in your traceback). You can convert it to python type using its to_python method. See example in readme.

js2py.eval_js(js).to_python()

I agree that may be a bit hard to use. I will modify eval_js function so that it returns python type automatically in the next version.

**Comment by Jake7zDunn** [comment]
Thanks for the quick response and for your work. Now works.
