### ISSUE TITLE
Using JS libraries with DOM object dependencies fails

### ISSUE THREAD

**Issue by dmwelch** [PiotrDabkowski/Js2Py#40]
I'm trying to use [Leaflet](http://leafletjs.com/index.html) so I can use it thus:
```python
import urllib, js2py
x = urllib.urlopen("http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet-src.js")
js = js2py.EvalJs()
js.execute(x.read())
script = """
function convert(lat, lng) {
  var latlng = L.latLng(lat, lng);
  var map = L.map('map');
  var point = map.project(latlng, 12).round();
  return point;
}"""
js.convert(52.7, 156.4)
```
The result is a "PyJsException: ReferenceError: L is not defined" error.  

I _believe_ it's due to the DOM dependancies (**window** and **document**) of the Leaflet library:
```javascript
/*
 Leaflet, a JavaScript library for mobile-friendly interactive maps. http://leafletjs.com
 (c) 2010-2013, Vladimir Agafonkin
 (c) 2010-2011, CloudMade
*/
(function (window, document, undefined) {
var oldL = window.L,
    L = {};
 ...
```

JS is not my thing (hence my patronage of js2py 😃), so maybe someone with more knowledge can kick this in the right direction...

**Comment by PiotrDabkowski** [comment]
Hey, I am sorry but Js2Py is not a browser and you will not be able to run JS that uses DOM. I thought about implementing a fake dom but that would take too much time. You can extract a part of JS source code that does not use dom and run it. Convert function may not use dom

**Comment by dmwelch** [comment]
Fair enough. :|

**Comment by apalala** [comment]
Hey @PiotrDabkowski, Following up on this, couldn't there be a _"fake"_ DOM implementation? Just enough to let the scripts out there succeed.

Something that could help on that path is a _mode_ in which `js2py` creates undefined variables with, types in agreement with their use, instead of failing on undefineds.

**Comment by worstperson** [comment]
You can't do a complex dom without a great amount of work, but you can make a stub dom that implements the minimum that your target code requires quite easily. This is especially true with webpages where you fail loading libraries and some script statements, but still succeed in executing specific scripts statements you are interested in.

**Comment by apalala** [comment]
If there are examples of such _stub_ DOM implementations, we could collaborative work on one that handles most of the scripts found on the Web. Do you know of any?
