### ISSUE TITLE
wrapper script for standalone use ?

### ISSUE THREAD

**Issue by UniqueFool** [PiotrDabkowski/Js2Py#43]
Hi, is there some kind of mode (or wrapper script) to use js2py as a standalone tool ?
Specifically, I want to port a bunch of existing javascript unit tests to Python, including the unit testing framework itself - I noticed, that you already have a import_js() API - would that be something that can be exposed for standalone use ?

Thank you

**Comment by PiotrDabkowski** [comment]
Hey, I am not sure what you mean. What do you mean by standalone tool?

**Comment by UniqueFool** [comment]
Hi, thanks for getting back in touch so quickly.
I was referring to the use of  js2py in a scripted fashion, i.e. in a shell environment.
The import_js() API seems to be suitable for using it that way, what do you think ?

Thanks

**Comment by Lexcon** [comment]
What do you need this for?

It's no so hard to envision a python program that expects an input file 
as a parameter, then runs it as a javascript.

Or do you mean more like an interactive prompt, in which case the 
examples already provide for that?

Robert

**Comment by UniqueFool** [comment]
yes, non-interactively like you say - it is for converting a bunch of unit tests to Python, to test the converted unit testing framework

**Comment by PiotrDabkowski** [comment]
I added `run_file` function.  It executes given path or file containing JS code and returns a tuple (eval_return, context).  You can use the same context to execute many files. update your js2py to use it.

**Comment by UniqueFool** [comment]
thanks, I will take a look - and thanks again for being so responsive, much appreciated !!

**Comment by UniqueFool** [comment]
Regarding the esprima js/py example: Is the serialization mechanism documented anywhere, i.e. can the AST be easily traversed/inspected or customized?

**Comment by UniqueFool** [comment]
What is the recommended way to translate a whole set of related scripts - specifically, I would like to get a log-file for all translations that failed for some reason, so that I can take a look.

Thank you
