### ISSUE TITLE
Python 2.6 not supported

### ISSUE THREAD

**Issue by petmakris** [PiotrDabkowski/Js2Py#46]
Python 2.6 is not supported. 

The included translator pyjsparser.py is not supporting 2.6. Also I don't know what else...

Also in setup.py , in nstall_requires = ['tzlocal>=1.2', 'six>=1.10'],
the pyjsparser is not stated although it included in your source tree...

If you could depent on pyjsparser externally in this project I could fix python 2.6 support of pyjsparser.

**Comment by TiberiumPY** [comment]
Python 2.6 is old....
Maybe close this issue?
wontfix ?

**Comment by PiotrDabkowski** [comment]
Hey, I will look into it

**Comment by PiotrDabkowski** [comment]
Done!
