### ISSUE TITLE
Error while using with Bezier.js

### ISSUE THREAD

**Issue by lgcc** [PiotrDabkowski/Js2Py#47]
I have used Js2Py with [Bezier.js](https://github.com/Pomax/bezierjs), writing code as below:
```python
js = js2py.EvalJs(open('bezier.js').read())
js.execute("""
  var curve = new Bezier(100, 25, 10, 90, 110, 100, 132, 192);
  curve.offset(25);  // it cause TypeError: PyJsLvalInline() takes exactly 2 arguments (4 given)
""")
```

then I switched to PyV8, it works fine. I don't know why, just tell u.

**Comment by PiotrDabkowski** [comment]
Thank you for letting me know. Fixed. Anyway I think PyV8 is a better option if it works for you, faster and more reliable :)

**Comment by Lexcon** [comment]
Piotr,

I remember you stating this before. How are you sure it's even faster?

When you need plenty of small js snippets to run with each of them 
accessing plenty of python functions and plenty of variables made 
available, I assume it's also causing overhead marshalling the Python 
variables and functions over to V8 and back.

I have to say I'm no expert in PyV8 but the fact that is crosses a 
process border in windows seems a slow step that cannot be avoided. Did 
anybody ever even do benchmark tests on this?

I'm aware that your library is pretty inefficient but who knows what 
ineficiency is there on the other side of the fence.

Robert

**Comment by PiotrDabkowski** [comment]
Hey Robert,

I tested it on my test suite - about 12000 tests - and it outperformed Js2Py in terms of both speed and accuracy. PyV8 was about 10 times faster.  No wonder, Google spent lots of money on V8 and I cant compete with them haha   

Even here `curve.offset(25) ` takes about 5 seconds on my computer :)

**Comment by PiotrDabkowski** [comment]
Also I am done with my exams so I will try to compile everything with Cython soon
