### ISSUE TITLE
Convert file

### ISSUE THREAD

**Issue by Trudko** [PiotrDabkowski/Js2Py#49]
Hi, it's possible to convert javascript file to python with Js2Py?

**Comment by PiotrDabkowski** [comment]
Hey, yes it is. Just use `translate_file` function. After translation everything is stored in `var` object.

```
import js2py
js2py.translate_fule('abc.js', 'abc.py')

from abc import var
abc = var.to_python()
```

**Comment by PiotrDabkowski** [comment]
Now you would have to do that manually, through js2py.translatr_js(js_code). I will add easier function that does everything automatically and supports easy imports tomorrow.

**Comment by shubshub** [comment]
From this I gather we can't load JS files? Have to manually copy-paste the code? and format it properly?

**Comment by PiotrDabkowski** [comment]
Added translate_file function so that you don't have to copy and paste anything. See readme for example.
