### ISSUE TITLE
JS code wasn't translated correctly to Python

### ISSUE THREAD

**Issue by kb01** [PiotrDabkowski/Js2Py#50]
Hello,

I'm getting an odd results after performing the JS code translation: like "**JS_BUILTINS**", "**PyJsHoisted**", "**PyJs_Object_0_**", "**:Js()**", "**var**". This is obviously a translation bug.

This is the detailed info about translation process: 

> python
> >>> import js2py
> >>> x = """
> ... /* -*- Mode: JS2; indent-tabs-mode: nil; js2-basic-offset: 4 -*- */
> ... /* vim: set et ts=4 sw=4: */
> ... /*
> ...  * Copyright (c) 2011, 2012, 2013 Red Hat, Inc.
> ...  *
> ...  * GNOME Maps is free software; you can redistribute it and/or modify
> ...  * it under the terms of the GNU General Public License as published by the
> ...  * Free Software Foundation; either version 2 of the License, or (at your
> ...  * option) any later version.
> ...  *
> ...  * GNOME Maps is distributed in the hope that it will be useful, but
> ...  * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
> ...  * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
> ...  * for more details.
> ...  *
> ...  * You should have received a copy of the GNU General Public License along
> ...  * with GNOME Maps; if not, see <http://www.gnu.org/licenses/>.
> ...  *
> ...  * Author: Cosimo Cecchi <cosimoc@redhat.com>
> ...  *         Zeeshan Ali (Khattak) <zeeshanak@gnome.org>
> ...  */
> ... 
> ... pkg.initGettext();
> ... pkg.initFormat();
> ... pkg.require({ 'cairo': '1.0',
> ...               'Champlain': '0.12',
> ...               'Clutter': '1.0',
> ...               'Cogl': '1.0',
> ...               'GeocodeGlib': '1.0',
> ...               'Gdk': '3.0',
> ...               'GdkPixbuf': '2.0',
> ...               'GFBGraph': '0.2',
> ...               'Gio': '2.0',
> ...               'GLib': '2.0',
> ...               'Goa': '1.0',
> ...               'GObject': '2.0',
> ...               'Gtk': '3.0',
> ...               'GtkChamplain': '0.12',
> ...               'GtkClutter': '1.0',
> ...               'Rest': '0.7',
> ...               'Soup': '2.4' });
> ... 
> ... const Application = imports.application;
> ... 
> ... function main(args) {
> ...     var application = new Application.Application();
> ...     return application.run(args);
> ... }
> ... """
> >>> js2py.translate_js(x)
> "from js2py.pyjs import *\n# setting scope\nvar = Scope( JS_BUILTINS )\nset_global_object(var)\n\n# Code follows:\nvar.registers(['main', 'Application'])\n@Js\ndef PyJsHoisted_main_(args, this, arguments, var=var):\n    var = Scope({'arguments':arguments, 'args':args, 'this':this}, var)\n    var.registers(['application', 'args'])\n    var.put('application', var.get('Application').get('Application').create())\n    return var.get('application').callprop('run', var.get('args'))\nPyJsHoisted_main_.func_name = 'main'\nvar.put('main', PyJsHoisted_main_)\nvar.get('pkg').callprop('initFormat')\nPyJs_Object_0_ = Js({'cairo':Js('1.0'),'Champlain':Js('0.12'),'Clutter':Js('1.0'),'Cogl':Js('1.0'),'GeocodeGlib':Js('1.0'),'Gdk':Js('3.0'),'GdkPixbuf':Js('2.0'),'GFBGraph':Js('0.2'),'Gio':Js('2.0'),'GLib':Js('2.0'),'Goa':Js('1.0'),'GObject':Js('2.0'),'Gtk':Js('3.0'),'GtkChamplain':Js('0.12'),'GtkClutter':Js('1.0'),'Rest':Js('0.7'),'Soup':Js('2.4')})\nvar.get('pkg').callprop('require', PyJs_Object_0_)\nvar.put('Application', var.get('imports').get('application'))\npass\npass\n"
> >>> 

Please fix this bug as soon as possible.

Thanks.

**Comment by PiotrDabkowski** [comment]
The translation works just fine, this is the only way to accurately mimic JS objects in Python. For example I had to keep all variables under `var` scope object in order to allow names like $ and more importantly to support JS function closures which are different from Python.
