### ISSUE TITLE
Recursion depth error on large Js files using translated esprima.js

### ISSUE THREAD

**Issue by Hucaru** [PiotrDabkowski/Js2Py#53]
SOLUTION:

Change python's recursion limit to ~4k.
___________________________
Found a potential issue while parsing large files such as angular.js (1.5.8).

```
file = open("angular.js")
input = file.read()
file.close()

#import esprima
ast = esprima.parse(input)
```

This produces a `RecursionError: maximum recursion depth exceeded` error with a stack trace showing calls to the following:

```
return Js(self.code(*args))
var.put('result', var.get('parser')())
return self.call(self.GlobalObject, args)
arguments = PyJsArguments(args, self) # tuple will be converted to arguments object.
RecursionError: maximum recursion depth exceeded
```

In python 3 the following error is also thrown:

```
During handling of the above exception, another exception occurred:
.
.
.
return Js(self.code(*args))
var.put('expr', var.get('inheritCoverGrammar')((var.get('parseNewExpression') if var.get('matchKeyword')(Js('new')) else var.get('parsePrimaryExpression'))))
return self.call(self.GlobalObject, args)
raise MakeError('RangeError', e.message if not isinstance(e, NotImplementedError) else 'Not  implemented!')
AttributeError: 'RecursionError' object has no attribute 'message'
```

The `parse_js()` function can parse the input without error.

**Comment by PiotrDabkowski** [comment]
This is because each Js function call = about 2-4 python function calls. Python has default recursion limit set to 1000 so it is much easier to reach this limit when using js2py. Try setting the recursion limit to 4k via sys and check if it works.

**Comment by Hucaru** [comment]
Thanks that has solved the issue. I shall edit the post to show the solution. Have you had the chance to look into issue #52?
