### ISSUE TITLE
getTimezoneOffset return value with wrong sign

### ISSUE THREAD

**Issue by felyxjet** [PiotrDabkowski/Js2Py#55]
As title says, getTimezoneOffset is wrong. I'm in UTC+3 and `js2py.eval_js('(new Date).getTimezoneOffset()')` returns 180, while it should be -180.

**Comment by PiotrDabkowski** [comment]
Hey, sorry for that error, will fix it today.

**Comment by PiotrDabkowski** [comment]
Fixed
