### ISSUE TITLE
How can I implement 'setTimeout'?

### ISSUE THREAD

**Issue by surpassly** [PiotrDabkowski/Js2Py#67]
I only want to execute the callback with out delay.

**Comment by PiotrDabkowski** [comment]
Without delay it's rather simple, you have 2 options. You can either implement it in Python or in JavaScript.

Python:

```
def setTimeout(func, delay):
    func()

ctx = js2py.EvalJs({'setTimeout': setTimeout})
# afterwards you can simply use
ctx.eval("setTimeout(function k() {console.log('timeout reached!')})")
```

JavaScript - you can simply prepend your Js code with a definition of setTiemout. 

`js_code = 'function setTimeout(func, delay) {func()}' + js_code`
