### ISSUE TITLE
js2py.base.PyJsException: ReferenceError: Uint32Array is not defined

### ISSUE THREAD

**Issue by twardoch** [PiotrDabkowski/Js2Py#70]
I'd like to try converting [svgo](https://github.com/svg/svgo) to Python. I've translated the "inlined" version of `svgo` available as [plugin.js](https://github.com/BohemianCoding/svgo-compressor/blob/master/SVGO%20Compressor.sketchplugin/Contents/Sketch/plugin.js) using js2py, see [Sketch.zip](https://github.com/PiotrDabkowski/Js2Py/files/694553/Sketch.zip)

I'm getting: 

```
  File "plugin.py", line 6587, in PyJs_anonymous_395_
    var.put(u'SYMBOL_CATEGORY', var.get(u'Uint32Array').create(var.get(u'SYMBOL_CATEGORY_LENGTH')))
  File "/Users/adam/Library/Python/2.7/lib/python/site-packages/js2py/base.py", line 1008, in get
    return self.prototype.get(prop, throw)
  File "/Users/adam/Library/Python/2.7/lib/python/site-packages/js2py/base.py", line 1013, in get
    raise MakeError('ReferenceError', '%s is not defined' % prop)
js2py.base.PyJsException: ReferenceError: Uint32Array is not defined
```

**Comment by PiotrDabkowski** [comment]
`Uint32Array ` is not a part of ECMA 5.1. It's a built-in object that is defined by ECMA 6.  Maybe some day I will implement some more built-in objects.

**Comment by twardoch** [comment]
Thank you for your explanations here and on the other threads! :)
