### ISSUE TITLE
Is there any way to limit scope?

### ISSUE THREAD

**Issue by DataGreed** [PiotrDabkowski/Js2Py#77]
Right now, as I understand, eval_js resulting code does not have any access to locals, globals or to other variables.

Is there any way to pass some dictionary with variables that evaluated will have access to?

E.g. like stdlib does it - they allow you to pass any dictionary to the scope of evaluated code.

**Comment by PiotrDabkowski** [comment]
I am not sure what you mean, do you want to pass something from Python to Js or the other way round?

You can easily get access to anything from JS scope by simply returning `this` (a global object).

```python
this = eval_js("a = 11; this")
this.a  # contains 11
```

From Python to Js is also very easy. You can simply create EvalJs which takes a context containing python stuff as a dictionary, see readme for example.
