### ISSUE TITLE
Tuples from pyimport functions get converted to lists

### ISSUE THREAD

**Issue by amv** [PiotrDabkowski/Js2Py#86]
In my `p.py` i have the following:

```
def tuple():
    return( ( 1, 2 ) )
def list():
    return( [ 1, 2 ] )
def compare( v1, v2 ):
    print str( v1.__dict__ ) == str( v2.__dict__ )
    print str( v1._obj.__dict__ ) == str( v2._obj.__dict__ )
```

And when I run this, I see no differences:

```
python -c 'import js2py; js2py.eval_js("pyimport p; p.compare( p.tuple(), p.list() );")'
True
True
True
```

For some reason the third True get's printed when I do `pyimport p;`, but this is irrelevant for this issue.

**Comment by PiotrDabkowski** [comment]
As mentioned in #87 both `tuple` and `list` are converted to the same JS Array when entering JS runtime. When leaving JS runtime JS Array is converted to py list.
