### ISSUE TITLE
Tidying up the license info.

### ISSUE THREAD

**Issue by techdragon** [PiotrDabkowski/Js2Py#9]
I've opened a pull request #8 to clean up the license information a little bit. 
Having a license file say the code is under MIT, but `setup.py` indicate that it is under GPL creates  confusion.

I've changed `setup.py` from GPL to MIT in the linked pull request, since you have only recently added the explicit license.txt file where as the GPL keyword in `setup.py` was in the first commit of that file, and choosing to add an entire license file seems like a clear decision on which license you actually wanted to use for the project.

**Comment by PiotrDabkowski** [comment]
Done, thank you! I don't know much about license stuff :)
